blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),  # using the url her specifies here(project level) is very good because the url will be used by diffeent applications
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name = 'logout'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name = 'password_reset_complete'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name = 'password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('', include('user.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from PIL import Image

# Create your models here.
class Profile(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/profile-picture.jpg', upload_to='profile_pics/')
    bio = models.TextField(blank=True)
    country = CountryField(default='US')
    date_of_birth = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'
    


    def save(self, *args, **kwargs):
        # Call the original save method
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        #check if our current image is greater than 300pixel
        if img.height>200 or img.width >200:

            output_size = (200, 200)

            img.thumbnail(output_size)

            # Save the resized image, overwriting the original image file
            img.save(self.image.path)

blog/templates/comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comment Section</title>
    <style>
        .comment-section {
            position: relative;
            overflow-y: auto;
            height: 800px;
            border: 1px solid #008080;
            padding: 10px;
            bottom: 0;
            left: 0;
            width: 100%;
            border-radius: 20px;
            
            
        }

        .comment-section::-webkit-scrollbar {
            width: 10px;
            background-color: transparent;
        }

        .comment {
            margin-bottom: 20px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 10px;
            display: flex;
            align-items: flex-start;
        }

        .comment .author {
            font-weight: bold;
            margin-right: 10px;
        }

        .comment .author img {
            width: 50px;
            height: 50px;
            border-radius: 50%;
        }

        .comment .comment-text {
            flex: 1;
        }

        .comment .date {
            color: #666;
            font-size: 0.8em;
        }

        #id_image {
            margin-bottom: 10px;
        }

        .comment-textarea {
            border: 1px solid #008080;
            border-radius: 20px;
            padding: 10px;
            width: 900px;
            margin-bottom: 10px;
            resize: none;
            overflow: hidden;
            box-sizing: border-box;
            font: inherit; /* Ensuring identical styling with the pseudo-element */
            }

            .comment-form .form-controls textarea {
            flex: 1;
            margin-bottom: 10px;
            }

            .grow-wraps {
            display: grid;
            }

            .grow-wraps::after {
            content: attr(data-replicated-value) " ";
            white-space: pre-wrap;
            visibility: hidden;
            }

            .grow-wraps > textarea,
            .grow-wraps::after {
            border: 1px solid #008080;
            border-radius: 20px;
            padding: 10px;
            width: 750px;
            box-sizing: border-box;
            font: inherit;
            grid-area: 1 / 1 / 2 / 2;
            }

        .comment-form {
            display: flex;
            align-items: flex-start;
        }

        .comment-form img {
            margin-right: 10px;
        }

        .comment-form .form-controls {
            display: flex;
            flex-direction: column;
            width: 100%;
        }

        .comment-form .form-controls textarea {
            flex: 1;
            margin-bottom: 10px;
        }

        .comment-form .form-controls input[type="submit"] {
            align-self: flex-start;
            margin-top: 20px;
            border-radius: 20px;
        }
    </style>
</head>
<body>
    <div class="comment-section" style="display: none;">
        <h3>Leave a Comment</h3>
        <form class="comment-form" method="post" action="{% url 'article_comment' article.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            
            <img src="{{ user.profile.image.url }}" style="width: 50px; height: 50px; border-radius: 50%;" alt="user">
            
            <div class="form-controls">
                <div class="grow-wraps">
                  <textarea name="c_ment" rows="1" cols="20" placeholder="Leave a comment for {{ article.author.username }}" class="comment-textarea" required onInput="this.parentNode.dataset.replicatedValue = this.value"></textarea>
                </div>
                <input type="submit" value="Comment" class="button primary small">
              </div>
        </form>
        {% include 'comment_listing.html' %}
    </div>
</body>
</html>

blog/templates/comment_listing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
     @import url(http://fonts.googleapis.com/css?family=Calibri:400,300,700);

            body {
                font-family: 'Calibri', sans-serif !important;
            }

            .label {
                padding: 3px 10px;
                line-height: 13px;
                color: #ffffff;
                font-weight: 400;
                border-radius: 4px;
                font-size: 75%;
            }

            .round img {
                border-radius: 100%;
            }

            .label-info {
                background-color: #1976d2;
            }

            .label-success {
                background-color: green;
            }

            .label-danger {
                background-color: #ef5350;
            }

            .action-icons a {
                padding-left: 7px;
                vertical-align: middle;
                color: #99abb4;
            }

            .action-icons a:hover {
                color: #1976d2;
            }

            .mt-100 {
                margin-top: 100px
            }

            .mb-100 {
                margin-bottom: 100px
            }
            .buttonload {
            background-color: rgba(245, 239, 239, 0.075);
            border-radius: 15px; /* Remove borders */
            color: white; /* White text */
            padding: 10px; /* Some padding */
            font-size: 9px; /* Set a font size */
            display: flex; /* Use flexbox */
            justify-content: center; /* Center horizontally */
            align-items: center; /* Center vertically */
            margin-bottom: 20px;
            }
            .buttonload i.fa-spinner {
            font-size: 20px; /* Set a larger font size for the spinner icon */
            }


            .modal {
                display: none;
                position: fixed;
                z-index: 1000;
                left: 0;
                top: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0, 0, 0, 0.5);
            }

            .modal-content {
                background-color: #006767;
                border-radius: 4px;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
                padding: 20px;
                max-width: 300px;
                max-height: 150px;
                margin: auto;
                text-align: center;
                font-size: 14px;
            }

            .buttons {
                display: flex;
                justify-content: center;
                margin-top: -20px;
            }

            button {
                border: none;
                padding: 5px 7px;
                border-radius: 4px; /* Make buttons rectangular */
                cursor: pointer;
                margin: 0 5px; /* Adjust margin */
                font-size: 7px;
                text-transform: uppercase; /* Make text uppercase */
            }

            .confirm-delete {
                background-color: #1976d2;
                color: white;
            }

            .cancel-delete {
                background-color: gray;
                color: black;
            }

            button:hover {
                opacity: 0.8; /* Adjust opacity on hover */
            }
            .comment-likes.liked i.fa-heart {
            color: red; 
		    }


            .card-no-border .card {
                border: 0px;
                border-radius: 4px;
                -webkit-box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.05);
                box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.05)
            }

            .card-body {
                -ms-flex: 1 1 auto;
                flex: 1 1 auto;
                padding: 1.25rem;
                
            }

            .comment-widgets .comment-row:hover {
                position: relative;
                 overflow-y: auto;
                background: #003738;
                cursor: pointer;
                width: 820px;
                border-radius: 15px;
                
            }
            .comment-widgets .comment-row:hover::-webkit-scrollbar {
            width: 10px;
            background-color: transparent;
        }
            .comment-widgets .date {
                color:#ffffff;
            }

            .comment-widgets .comment-row {
                border-top: 1px solid #008080;
                border-bottom: 1px solid #008080;
                border-right: 1px solid #008080;
                border-left: 1px solid #008080;
                border-radius: 15px;
                margin-top: 10px;
                padding: 15px;
                width: 820px;
            }

            .comment-text:hover{
                visibility: visible;
            }

            .label {
                padding: 3px 10px;
                line-height: 13px;
                color: #ffffff;
                font-weight: 400;
                border-radius: 4px;
                font-size: 75%;
            }

            .round img {
                border-radius: 100%;
            }

            .label-info {
                background-color: #1976d2;
            }

            .label-success {
                background-color: green;
            }

            .label-danger {
                background-color: #ef5350;
            }

            .action-icons a {
                padding-left: 7px;
                vertical-align: middle;
                color: #99abb4;
            }

            .action-icons a:hover {
                color: #1976d2;
            }

            .mt-100 {
                margin-top: 100px
            }

            .mb-100 {
                margin-bottom: 100px
            }
            
            .action-icons{
                margin-left: 550px;
            }


    </style>
</head>
<body>            
    
    <div class="container d-flex justify-content-center mt-100 mb-100">
      <div class="row">
          <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Comments</h6>
                 </div>
                
                <div class="comment-widgets m-b-20" data-article-id="{{ article.id }}">
                    {% for comment in article.article_comments %}
                    <div class="d-flex flex-row comment-row" data-comment-id="{{ comment.id }}">  
                        <div class="p-2"><span class="round"><img src="{{comment.author.profile.image.url}}" style="width: 45px; height: 45px; border-radius: 50%;" alt="user" width="50"></span></div>
                        <div class="comment-text w-100">
                            <h5>{{ comment.author }}</h5>
                            <p class="m-b-5 m-t-10"> {{comment.c_ment}}</p>
                            <div class="comment-footer">
                                <span class="date">{{comment.get_date}}</span>
                                 <span class="action-icons">
                                    {% if comment.author == user %}
                                            <a href="#" class="delete-comment" data-comment-id="{{ comment.id }}"><i class="fa fa-trash trash-icon"></i></a> 
                                    {% endif %}
                                        
                                        <a href="#" class="comment-likes" data-comment-id="{{ comment.id }}">
                                            <i class="fas fa-heart like-icon"></i> 
                                            <span class="like-icons">{{ comment.comment_likes.count }}</span> 
                                        </a>
                                        <a href="#" class="icon solid toggle-replies" data-comment-id="{{ commment.id }}">
											<i class="fas fa-comment"></i>
											<span class="comment-count">5</span>
										</a>
                                </span>
                            
                            </div>
                            <div class="replies-section" data-comment-id="{{ comment.id }}" style="display: none;">
                                <h3>Replying to @{{ comment.author }}</h3>
                                <form class="reply-form" method="post" action="{% url 'comments_replies' comment.id %}">
                                  {% csrf_token %}
                                  <img src="{{ user.profile.image.url }}" style="width: 50px; height: 50px; border-radius: 50%;" alt="user">
                                  <div class="form-controls">
                                    <div class="grow-wrap">
                                      <textarea name="reply_text" rows="1" cols="20" placeholder="Leave a comment for {{ comment.author }}" class="comment-textarea" required onInput="this.parentNode.dataset.replicatedValue = this.value"></textarea>
                                    </div>
                                    <input type="submit" value="Reply" class="button primary small">
                                  </div>
                                </form>
                            {% include 'reply_listing.html' %}
                            </div>
                            <!-- remplate to handle delete confirmation-->
                            <div class="custom-confirm" data-comment-id="{{ comment.id }}" style="display: none;">
                                <div class="modal-content">
                                    <p><strong>Delete</strong><br>Are you sure that you want to delete this comment?</p>
                                    <div class="buttons">
                                        <button class="confirm-delete">Delete</button>
                                        <button class="cancel-delete">Cancel</button>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        
                       
                    </div>
                    {% endfor %}
                </div>
               
            </div>
    
          </div>
      </div>
    </div>
    
    {% if article.article_comments.has_other_pages %}
    <div class="pagination">
        {% if article.article_comments.has_previous %}
            <!-- Pagination links -->
            {% for num in article.article_comments.paginator.page_range %}
                {% if article.article_comments.number == num %}
                    <span class="page current">{{ num }}</span>
                {% else %}
                    <a href="?article_id={{ article.id }}&page={{ num }}" class="page" data-current-page="{{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}  
        {% endif %}
        {% if article.article_comments.has_next %}
            <button class="buttonload" data-article-id="{{ article.id }}" data-current-page="{{ article.article_comments.number }}">
                <i class="fa fa-spinner"></i> Load More
            </button>
        {% endif %}
    </div>
    {% endif %}      
    

  </body>
</html>

blog/templates/email-verification-sent.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>

    
<style>
	body {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #003738; /* Light background for better contrast */
    padding: 15px;
}
   .form-container {
       width: 500px;
       margin-left: 400px;
	   background: #004e4f;
   }
   .custom-alert {
    max-width: 500px;
    }
	.active-text{
		color:#fff;
	}
	.icon-light-green {
    color: lightgreen;
}
.custom-alert{
    margin-left: 400px;
}
   
</style>


				<!-- Main -->
					<div id="main">
						{% if messages %}
    					{% for message in messages %}
      					  <div class="alert alert-{{ message.tags }} custom-alert">
           				 {{ message }}
        				</div>
   						 {% endfor %}
						{% endif %}
						<!-- Post -->
                        <div class = "form-container container shadow-md p-5"> 
                            <div class ="text-center">
                                <i class="fa fa-envelope fa-3x icon-light-green" aria-hidden="true"></i>
                            <br><br>
                    
                            <h5><strong class = "active-text">  A verification link was sent to your email.</strong></h5>
                            <hr>
                            <br>
                    
                            <p class = 'email_p'> please check your email. </p>
                            </div>
                    </div>


					</div>

			

			</div>

	</body>
</html>
{% endblock %}

blog/templates/email-verification-success.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>
<style>
    /* Additional styles for form container */
    .form-container {
        width: 500px;
        margin-left: 400px;
		background: #004e4f;
    }

	body {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #003738; /* Light background for better contrast */
    padding: 15px;
}
	.active-text{
		color:#fff;
	}
    
   
    
 </style>


				<!-- Main -->
					<div id="main">
                        <div class = "form-container container shadow-md p-5"> 
                            <div class ="text-center">
                                    <i class="fa fa-check fa-3x text-success" aria-hidden="true"></i>
                                <br><br>
                        
                                <h5><strong class="active-text"> Your account is active! </strong></h5>
                                <hr>
                        
                                <p> Please proceed to log in. </p>
                                <br>
								<a href="{% url 'login' %}" class="button large fit" style ="width:150px; height: 50px;">Sign In</a>
                            </div>
                        </div>
                    </div>

			</div>

	</body>
</html>
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<head>

</head>
</head>
<style>
    

	body {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #003738; /* Light background for better contrast */
    padding: 15px;
}
   .form-container {
	display:flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
    width: 600px;
	height: 700px;
    margin-left: 450px;
	background: #004E4F;
   }
   .text-muted{
	color:#fff;
   }

   
</style>

<body>
				<!-- Main -->
					<div id="main">
                        <div class = "form-container container bg-white shadow-md p-5"> 
                            <h3>Login to your account</h3>
                            <BR><BR>
                            <h5>Compose your Favorite Post Today</h5>
                            <br>
                            <form method="POST" autocomplete="off">
                                {% csrf_token %}
                                {{form|crispy}}   
                        <br>
								<button type ="submit" id ="sub_btn" class="btn btn-sm" style ="width:150px; height: 50px;"> &nbsp; Sign IN </button>
								<br><br>
								<small class="text-muted">
                            	<a class="ml-2" href="{% url 'password_reset' %}"> Forgot Password?</a>
                                </small>
                
                            </form>
                            <div class=""border-top pt-3">
                                <small class="text-muted">
                                    You don't have an account? <a class="ml-2" href="{% url 'register' %}"> Sign up</a>
                                </small>
                            
                            
                            </div>
                        
                    	</div>


					</div>

	</body>
</html>
{% endblock %}

blog/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<head>

</head>
</head>
<style>
    

	body {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #003738; /* Light background for better contrast */
    padding: 15px;
}
   .form-container {
	display:flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
    width: 700px;
	height: 500px;
    margin-left: 400px;
	background: #004E4F;
   }
   .text-muted{
	color:#fff;
   }

   
</style>

<body>
				<!-- Main -->
					<div id="main">

						<!-- Post -->
							
						<!-- Post -->
                        <div class = "form-container container  shadow-md p-5"> 
                            <h3>You have been signed out</h3>
                            <BR>
                            <h5> Sign in to compose your Favorite Post Today</h5>
                            <br>
                            <form method="POST" autocomplete="off">
                                {% csrf_token %}
                                {{form|crispy}}   
                        <br>
                                <a href="{% url 'login' %}" class="button large fit" style ="width:150px; height: 50px;">Sign In</a>
                            </form>
                            <div class=""border-top pt-3">
                                <small class="text-muted">
                                    You don't have an account? <a class="ml-2" href="{% url 'register' %}"> Sign up</a>
                                </small>
                            
                            
                            </div>
                        
                    	</div>


					</div>

	</body>
</html>
{% endblock %}

blog/templates/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<head>

</head>
</head>
<style>
    

   /* Additional styles for form container */
   .form-container {
       width: 500px;
       height:1500px;
       margin-left: 10px;
   }
   
</style>


				<!-- Main -->
					<div id="main">

						<!-- Post -->
							
						<!-- Post -->
                        <div class = "form-container container bg-white shadow-md p-5"> 
                            <h3>Reset Password</h3>
                            <BR><BR>
                            <h5>Input your registered email to reset password</h5>
                            <br>
                            <form method="POST" autocomplete="off">
                                {% csrf_token %}
                                {{form|crispy}}   
                        <br>
								<button type ="submit" id ="sub_btn" class="btn btn-sm" style ="width:250px; height: 50px;"> &nbsp;Request Password Reset</button>
                
                            </form>
                        
                    	</div>


					</div>

				<!-- Sidebar -->
					<section id="sidebar">

						<!-- Intro -->
							<section id="intro">
								<a href="#" class="logo"><img src="{% static 'images/logo.jpg' %}" alt="" /></a>
								<header>
									<h2>Future Imperfect</h2>
									<p>Another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a></p>
								</header>
							</section>

						<!-- Mini Posts -->
							<section>
								<div class="mini-posts">

									<!-- Mini Post -->
										<article class="mini-post">
											<header>
												<h3><a href="single.html">Vitae sed condimentum</a></h3>
												<time class="published" datetime="2015-10-20">October 20, 2015</time>
												<a href="#" class="author"><img src="{% static 'images/avatar.jpg' %}" alt="" /></a>
											</header>
											<a href="single.html" class="image"><img src="{% static 'images/pic04.jpg' %}" alt="" /></a>
										</article>
								</div>
							</section>

						<!-- Posts List -->
							<section>
								<ul class="posts">
									<li>
										<article>
											<header>
												<h3><a href="single.html">Lorem ipsum fermentum ut nisl vitae</a></h3>
												<time class="published" datetime="2015-10-20">October 20, 2015</time>
											</header>
											<a href="single.html" class="image"><img src="{% static 'images/pic08.jpg' %}" alt="" /></a>
										</article>
									</li>
								</ul>
							</section>

						<!-- About -->
							<section class="blurb">
								<h2>About</h2>
								<p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>
								<ul class="actions">
									<li><a href="#" class="button">Learn More</a></li>
								</ul>
							</section>

						<!-- Footer -->
							<section id="footer">
								<ul class="icons">
									<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
									<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
								</ul>
								<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
							</section>

					</section>

			</div>

	</body>
</html>
{% endblock %}