blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),  # using the url her specifies here(project level) is very good because the url will be used by diffeent applications
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name = 'logout'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name = 'password_reset_complete'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name = 'password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('', include('user.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/index/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from django.utils.timesince import timesince
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django_resized import ResizedImageField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
from django.contrib.humanize.templatetags import humanize

# Create your models here
class Article(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length =2000, default="enjoy your reading")
    preview = models.TextField(default="Click on continue reading to read all")
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    image = ResizedImageField(size=[1000,400 ], crop=['middle', 'center'], default='profile_pics/profile-picture.jpg', upload_to='article_images/')
    likes_count = models.IntegerField(default=0) 
    comment_count = models.IntegerField(default=0) 




    def get_date(self):
        now = timezone.now()
        time_difference = now - self.date_posted

        if time_difference < timedelta(days=1):
            hours = time_difference.seconds // 3600
            return f"{hours} hour{'s' if hours != 1 else ''} ago"
        elif time_difference < timedelta(weeks=1):
            days = time_difference.days
            return f"{days} day{'s' if days != 1 else ''} ago"
        elif time_difference < timedelta(days=30):
            weeks = time_difference.days // 7
            return f"{weeks} week{'s' if weeks != 1 else ''} ago"
        else:
            months = time_difference.days // 30
            return f"{months} month{'s' if months != 1 else ''} ago"

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})




class Comments(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    c_ment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    comment_likes_count = models.IntegerField(default=0) 


    def get_date(self):
        now = timezone.now()
        time_difference = now - self.created_at

        if time_difference < timedelta(days=1):
            hours = time_difference.seconds // 3600
            return f"{hours} hour{'s' if hours != 1 else ''} ago"
        elif time_difference < timedelta(weeks=1):
            days = time_difference.days
            return f"{days} day{'s' if days != 1 else ''} ago"
        elif time_difference < timedelta(days=30):
            weeks = time_difference.days // 7
            return f"{weeks} week{'s' if weeks != 1 else ''} ago"
        else:
            months = time_difference.days // 30
            return f"{months} month{'s' if months != 1 else ''} ago"

    def __str__(self):
        return f"Comment by {self.author.username} on {self.created_at}: {self.c_ment}"
    


class Reply(models.Model):
    replies = models.ForeignKey(Comments, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    reply_text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    reply_count =models.IntegerField(default=0)


    def get_date(self):
        now = timezone.now()
        time_difference = now - self.created_at

        if time_difference < timedelta(days=1):
            hours = time_difference.seconds // 3600
            return f"{hours} hour{'s' if hours != 1 else ''} ago"
        elif time_difference < timedelta(weeks=1):
            days = time_difference.days
            return f"{days} day{'s' if days != 1 else ''} ago"
        elif time_difference < timedelta(days=30):
            weeks = time_difference.days // 7
            return f"{weeks} week{'s' if weeks != 1 else ''} ago"
        else:
            months = time_difference.days // 30
            return f"{months} month{'s' if months != 1 else ''} ago"

    def __str__(self):
        return f"Comment by {self.author.username} on {self.created_at}: {self.reply_text}"


    def __str__(self):
        return f"reply by {self.author.username} on {self.created_at}"







    

class Like(models.Model):
    post = models.ForeignKey(Article, related_name='likes', on_delete=models.CASCADE, default =1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.post.likes_count = self.post.likes.count()
        self.post.save()

    def delete(self, *args, **kwargs):
        post = self.post
        super().delete(*args, **kwargs)
        post.likes_count = post.likes.count()
        post.save()

    @property
    def total_likes(self):
        return self.likes.count()


class comment_likes(models.Model):
    comment = models.ForeignKey(Comments, related_name='comment_likes', on_delete=models.CASCADE, default =1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.comment.likes_count = self.comment.comment_likes.count()
        self.comment.save()

    def delete(self, *args, **kwargs):
        comment = self.comment
        super().delete(*args, **kwargs)
        comment.likes_count = comment.likes.count()
        comment.save()

    @property
    def total_likes(self):
        return self.comments_likes.count()
    




class reply_likes(models.Model):
    reply = models.ForeignKey(Reply, related_name='reply_likes', on_delete=models.CASCADE, default =1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.reply.likes_count = self.reply.reply_likes.count()
        self.reply.save()

    def delete(self, *args, **kwargs):
        reply = self.reply
        super().delete(*args, **kwargs)
        reply.likes_count = reply.likes.count()
        reply.save()

    @property
    def total_likes(self):
        return self.reply_likes.count()
    

blog/templates/index/article_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
</head>
<style>
    

   /* Additional styles for form container */
        .form-container {
            width: 500px;
            height:1500px;
            margin-left: 10px;
        }
        .btn_update {
			display: inline-block;
			width: 150px;
			height: 50px;
			margin-right: 10px; /* Adjust margin between buttons */
			border: 1px solid #e4dadb; /* Border color set to danger */
			font-weight: bold;
			padding: 0.25rem 0.5rem; /* Padding adjusted */
            font-size: 0.8rem;
            line-height: 1.5;
            border-radius: 0.25rem;
		}
        .btn {
            display: inline-block;
            font-weight: bold;
            color: #dc3545; /* Text color set to danger */
            text-align: center;
            vertical-align: middle;
            user-select: none;
            background-color: transparent; /* Transparent background */
            border: 1px solid #e4dadb; /* Border color set to danger */
            padding: 0.25rem 0.5rem; /* Padding adjusted */
            font-size: 0.8rem;
            line-height: 1.5;
            border-radius: 0.25rem;
            transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
            cursor: pointer;
            text-decoration: none;
        }

        .btn:hover {
            color: #fff;
            background-color: #dc3545; /* Background color on hover set to danger */
            border-color: #bd2130; /* Border color on hover set to danger */
            text-decoration: none;
        }

        .btn:focus {
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
        }

        .btn:active {
            color: #fff;
            background-color: #bd2130; /* Background color on active set to danger */
            border-color: #b21f2d; /* Border color on active set to danger */
        }
     
   

           


        



   
</style>


				<!-- Main -->
					<div id="main">
							
						<!-- Post -->
                        <div class = "form-container container bg-white shadow-md p-5"> 
                            <h2> Delete Article </h2>
                            <form method="POST" autocomplete="off">
                                {% csrf_token %}
                                <br>   
                                <h4>
                                    are you sure you want to delete this article?  "{{object.title}}"
                                </h4>
                                <br>
                                <div class="d-inline">
                                <button type="submit" id="sub_btn" class="btn" style="width: 150px; height: 50px;"> &nbsp;Yes, Delete
                                </button>
                                <button type="submit" href="{% url 'article-detail' object.id %}" id="sub_btn" class="btn_update" style="width: 150px; height: 50px;"> &nbsp;CANCEL</button>
                                </div>
                            </form>
							
                        
                    	</div>


					</div>

				<!-- Sidebar -->
					<section id="sidebar">

						<!-- Intro -->
							<section id="intro">
								<a href="#" class="logo"><img src="{% static 'images/logo.jpg' %}" alt="" /></a>
								<header>
									<h2>Future Imperfect</h2>
									<p>Another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a></p>
								</header>
							</section>

						<!-- Mini Posts -->
							<section>
								<div class="mini-posts">

									<!-- Mini Post -->
										<article class="mini-post">
											<header>
												<h3><a href="single.html">Vitae sed condimentum</a></h3>
												<time class="published" datetime="2015-10-20">October 20, 2015</time>
												<a href="#" class="author"><img src="{% static 'images/avatar.jpg' %}" alt="" /></a>
											</header>
											<a href="single.html" class="image"><img src="{% static 'images/pic04.jpg' %}" alt="" /></a>
										</article>
								</div>
							</section>

						<!-- Posts List -->
							<section>
								<ul class="posts">
									<li>
										<article>
											<header>
												<h3><a href="single.html">Lorem ipsum fermentum ut nisl vitae</a></h3>
												<time class="published" datetime="2015-10-20">October 20, 2015</time>
											</header>
											<a href="single.html" class="image"><img src="{% static 'images/pic08.jpg' %}" alt="" /></a>
										</article>
									</li>
								</ul>
							</section>

						<!-- About -->
							<section class="blurb">
								<h2>About</h2>
								<p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>
								<ul class="actions">
									<li><a href="#" class="button">Learn More</a></li>
								</ul>
							</section>

						<!-- Footer -->
							<section id="footer">
								<ul class="icons">
									<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
									<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
								</ul>
								<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
							</section>

					</section>

			</div>

	</body>
</html>
{% endblock %}

blog/templates/index/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
		.button-container {
			display: flex; /* Use flexbox to align buttons horizontally */
			justify-content: space-between; /* Adjust spacing between buttons */
		}
		

		.btn_update {
			display: inline-block;
			width: 100px;
			height: 50px;
			margin-left: 10px; /* Adjust margin between buttons */
			border: 1px solid #e4dadb; /* Border color set to danger */
			font-weight: bold;
			padding: 0.4rem 1.0rem; /* Padding adjusted */
            font-size: 0.8rem;
            line-height: 2.5;
            border-radius: 0.25rem;
			text-align: center; /* Center align text */
			vertical-align: middle;
			user-select: none;
			background-color: transparent; 
			text-decoration: none;
		}

		.btn_delete {
			display: inline-block;
			font-weight: bold;
			color: #dc3545; /* Text color set to danger */
			text-align: center; /* Center align text */
			vertical-align: middle;
			user-select: none;
			background-color: transparent; /* Transparent background */
			border: 1px solid #e4dadb; /* Border color set to danger */
			padding: 0.4rem 1.0rem; /* Padding adjusted */
			font-size: 0.8rem;
			line-height: 2.5;
			border-radius: 0.25rem;
			transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
			cursor: pointer;
			text-decoration: none;
			width: 100px;
			height: 50px;
			margin-left: 20px; /* Adjust margin between buttons */
		}

		.btn_delete:hover {
			color: #fff;
			background-color: #dc3545; /* Background color on hover set to danger */
			border-color: #bd2130; /* Border color on hover set to danger */
			text-decoration: none;
		}

		.btn_delete:focus {
			outline: 0;
			box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
		}

		.btn_delete:active {
			color: #fff;
			background-color: #bd2130; /* Background color on active set to danger */
			border-color: #b21f2d; /* Border color on active set to danger */
		}
		.btn_update:hover {
			color: #fff;
			background-color: #c3cfde; /* Background color on hover set to danger */
			border-color: #4a6b82; /* Border color on hover set to danger */
			text-decoration: none;
		}
		h3.view_posts {
			font-weight: bold;
			font-size: small;
		}






</style>


		
				
	<!-- Main -->
		<div id="main">
				<article class="post">
					<header>
						<div class="title">
							<h2><a href="#">{{object.title}}</a></h2>
							<p>{{object.sub_title}}</p>
						</div>
						<div class="meta">
							<time class="published" datetime="2015-11-01">{{object.date_posted|date:"F d, Y"}}</time>
							<a href="{% url 'profile' %}" class="author"><span class="name">{{object.author}}</span><img src="{{object.author.profile.image.url}}" alt="" style="width: 45px; height: 45px; border-radius: 50%;" /></a>
							<h3><a href="{% url 'user-article' article.author.username %}" class ="view_post"> VIEW POSTS</a></h3>
							{% if object.author == user %}
							<div class = "button-container">
							<a type="submit" class="btn btn_update" href="{% url 'article-update' object.id %}" style="width: 150px; height: 50px;"> &nbsp;Update</a>
							<a type="submit"  class=" btn btn_delete" href ="{% url 'article-delete' object.id %}" style="width: 150px; height: 50px;"> &nbsp;Delete</a>
							</div>
							{% endif %}
						</div>
					</header>
					<span class="image featured"><img src="{{object.image.url}}" alt="" /></span>
					<p>{{object.content}}</p>
					<p></p>
					<footer>
						<ul class="stats">
							<li><a href="#">General</a></li>
							<li><a href="#" class="icon solid fa-heart">28</a></li>
							<li><a href="#" class="icon solid fa-comment">128</a></li>
						</ul>
						
					</footer>
					
				</article>	
		</div>
			
    {% endblock %}

blog/templates/index/article_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<head>

</head>
</head>
<style>
    

   /* Additional styles for form container */
   .form-container {
       width: 500px;
       height:1500px;
       margin-left: 10px;
   }

   
</style>


				<!-- Main -->
					<div id="main">

						<!-- Post -->
							
						<!-- Post -->
                        <div class = "form-container container bg-white shadow-md p-5"> 
                            <h3>Create your account</h3>
                            <h5>Compose your Favorite Post Today</h5>
                            <br>
                            <form method="POST" autocomplete="off" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <br>   
                
								<button type ="submit" id ="sub_btn" class="btn btn-sm" style ="width:150px; height: 50px;"> &nbsp; Post </button>
                
                            </form>
							
                        
                    	</div>


					</div>

				<!-- Sidebar -->
					<section id="sidebar">

						<!-- Intro -->
							<section id="intro">
								<a href="#" class="logo"><img src="{% static 'images/logo.jpg' %}" alt="" /></a>
								<header>
									<h2>Future Imperfect</h2>
									<p>Another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a></p>
								</header>
							</section>

						<!-- Mini Posts -->
							<section>
								<div class="mini-posts">

									<!-- Mini Post -->
										<article class="mini-post">
											<header>
												<h3><a href="single.html">Vitae sed condimentum</a></h3>
												<time class="published" datetime="2015-10-20">October 20, 2015</time>
												<a href="#" class="author"><img src="{% static 'images/avatar.jpg' %}" alt="" /></a>
											</header>
											<a href="single.html" class="image"><img src="{% static 'images/pic04.jpg' %}" alt="" /></a>
										</article>
								</div>
							</section>

						<!-- Posts List -->
							<section>
								<ul class="posts">
									<li>
										<article>
											<header>
												<h3><a href="single.html">Lorem ipsum fermentum ut nisl vitae</a></h3>
												<time class="published" datetime="2015-10-20">October 20, 2015</time>
											</header>
											<a href="single.html" class="image"><img src="{% static 'images/pic08.jpg' %}" alt="" /></a>
										</article>
									</li>
								</ul>
							</section>

						<!-- About -->
							<section class="blurb">
								<h2>About</h2>
								<p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>
								<ul class="actions">
									<li><a href="#" class="button">Learn More</a></li>
								</ul>
							</section>

						<!-- Footer -->
							<section id="footer">
								<ul class="icons">
									<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
									<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
								</ul>
								<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
							</section>

					</section>

			</div>

	</body>
</html>
{% endblock %}

blog/templates/index/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}


<style>

			
		.form-container {
			width: 500px;
			height:1500px;
			margin-left: 10px;
		}
		.btn_update {
			display: inline-block;
			width: 150px;
			height: 50px;
			margin-right: 10px; /* Adjust margin between buttons */
			border: 1px solid #e4dadb; /* Border color set to danger */
			font-weight: bold;
			padding: 0.25rem 0.5rem; /* Padding adjusted */
			font-size: 0.8rem;
			line-height: 1.5;
			border-radius: 0.25rem;
		}
		.btn {
			display: inline-block;
			font-weight: bold;
			color: #dc3545; /* Text color set to danger */
			text-align: center;
			vertical-align: middle;
			user-select: none;
			background-color: transparent; /* Transparent background */
			border: 1px solid #e4dadb; /* Border color set to danger */
			padding: 0.25rem 0.5rem; /* Padding adjusted */
			font-size: 0.8rem;
			line-height: 1.5;
			border-radius: 0.25rem;
			transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
			cursor: pointer;
			text-decoration: none;
		}

		.btn:hover {
			color: #fff;
			background-color: #dc3545; /* Background color on hover set to danger */
			border-color: #bd2130; /* Border color on hover set to danger */
			text-decoration: none;
		}

		.btn:focus {
			outline: 0;
			box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
		}

		.btn:active {
			color: #fff;
			background-color: #bd2130; /* Background color on active set to danger */
			border-color: #b21f2d; /* Border color on active set to danger */
		}
		h3.view_posts {
			font-weight: bold;
			font-size: small;


		}
		.custom-heart {
			background-color: gray; /* Set the background color */
			padding: 0.2em; /* Adjust padding to control the size of the background */
			border-radius: 50%; /* Make the background circular */
			color: white; /* Set the color of the heart icon to white */
	}

		
		.like-button.liked i.fa-heart {
        color: red; 
		}

</style>


	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">

						<!-- Post -->
						{% for article in articles %}
						<article class="post">
							<header>
								<div class="title">
									<h2><a href="{% url 'article-detail' article.id %}">{{ article.title }}</a></h2>
									<p>{{ article.sub_title }}</p>
								</div>
								<div class="meta">
									<time class="published" datetime="2015-11-01">{{ article.date_posted|date:"F d, Y" }}</time>
									<a href="{% url 'profile' %}" class="author">
										<span style="font-weight: bold; margin-left: 30px;">{{ article.author.username }}</span>
										<img src="{{ article.author.profile.image.url }}" alt="" style="width: 45px; height: 45px; border-radius: 50%;" />
									</a>
									<h3><a href="{% url 'user-article' article.author.username %}" class="view_posts"> VIEW POSTS</a></h3>
								</div>
							</header>
							<a href="#" class="image featured"><img src="{{ article.image.url }}" alt="" /></a>
							<p>{{ article.preview }}</p>
							<footer>
								<ul class="actions">
									<li><a href="{% url 'article-detail' article.id %}" class="button large">Continue Reading</a></li>
								</ul>
								<ul class="stats">
									<li><a href="#">General</a></li>
									<li>
										<a href="#" class="like-button" data-article-id="{{ article.id }}">
											<i class="fas fa-heart like-icon"></i> 
											<span class="like-count">{{ article.likes.count }}</span> 
										</a>
									</li>
									<li>
										<a href="#" class="icon solid toggle-comment" data-article-id="{{ article.id }}">
											<i class="fas fa-comment"></i>
											<span class="comment-count">{{ article.comments_set.count }}</span>
										</a>
									</li>
								</ul>
							</footer>
							{% include 'comment_form.html' %}
						</article>
						{% endfor %}
						<!-- Pagination -->
							<ul class="actions pagination">
							{% if is_paginated %}
								{% if page_obj.has_previous %}
								<li><a href="?page=1" class="button medium previous">First</a></li>
								<li><a href="?page={{page_obj.previous_page_number}}" class="button medium previous">Previous Page</a></li>
								{% endif %}


								{% for num in page_obj.paginator.page_range %}
								  {% if page_obj.number == num %}
								  <li><a href="?page={{num }}" class="button medium previous">{{num }}</a></li>
								  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
								  <li><a href="?page={{num }}" class="button medium previous">{{num }}</a></li>
								{% endif %}
								{% endfor %}

								{% if page_obj.has_next %}
								  <li><a href="?page={{page_obj.next_page_number}}" class="button medium previous">Next</a></li>
								  <li><a href="?page={{ page_obj.paginator.num_pages }}" class="button medium previous">last</a></li>
								  {% endif %}
                           {% endif %}
							</ul>
							
					</div>

				<!-- Sidebar -->
					<section id="sidebar">
						<!-- Intro -->
							<section id="intro">
								<a href="#" class="logo"><img src="{% static 'images/aliens.jpg' %}" alt="" /></a>
								<header>
									<h2><a href="">COSMIC HUBOSPHERE</a></h2>
									
									<p>Your Portal to the  boundless realms of celestial exploration and artificial intelligence intergration. <a href="http://html5up.net"></a></p>
								</header>
							</section>

						<!-- Mini Posts -->
							<section>
								<div class="mini-posts">

									<!-- Mini Post -->
									{% for mini_post in articles %}
										<article class="mini-post">
											
											<header>
												<h4><a href="single.html">{{ mini_post.title}}</a></h4>
												<time class="published" datetime="2015-10-20">{{mini_post.date_posted|date:"F d, Y"}}</time>
												<a href="#" class="author"><img src="{{mini_post.author.profile.image.url}}" alt="" style="width: 45px; height: 45px; border-radius: 50%;"/></a>
											</header>
											<a href="single.html" class="image"><img src="{{ mini_post.image.url}}" alt="" /></a>
											{% endfor %}
										</article>

								</div>
							</section>

						<!-- Posts List -->
							<section>
								<ul class="posts">
									{% for list in articles %}
									<li>
										<article>
											<header>
												<h3><a href="single.html">{{list.title}}</a></h3>
												<time class="published" datetime="2015-10-20">{{list.date_posted|date:"F d, Y"}}</time>
											</header>
											<a href="single.html" class="image"><img src="{{ list.image.url}}" alt="" /></a>
										</article>
										{% endfor %}
									</li>
									
								</ul>
							</section>

						<!-- About -->
							<section class="blurb">
								<h2>About</h2>
								<p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>
								<ul class="actions">
									<li><a href="#" class="button">Learn More</a></li>
								</ul>
							</section>

						<!-- Footer -->
							<section id="footer">
								<ul class="icons">
									<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
									<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
								</ul>
								<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
							</section>

					</section>
					
			</div>
			
</body>
{% endblock %}